### ISSUE TITLE
Decrypt file in React Native

### ISSUE THREAD

**Issue by mikaoelitiana** [sounisi5011/npm-packages#325]
Hello, 

I am looking for a way to decrypt files encrypted on server with this module on mobile app using React Native. Do you know how to do that? 
This package does not work with React Native so I need to find another package for the mobile part.

Thanks for your help

**Comment by sounisi5011** [comment]
Thanks for your message!

Unfortunately, there is no alternative to the [`@sounisi5011/encrypted-archive`] package. The data generated by this package is in [a format][encrypted-archive-structure.md] specific to this package. Since I designed it, there is no other implementation.

However, [the data format][encrypted-archive-structure.md] uses [unsigned varint](https://github.com/multiformats/unsigned-varint) and [Protocol Buffers](https://developers.google.com/protocol-buffers/), so you should be able to decrypt the file without using this package. All you need is:

+ A decipher function that supports AES-GCM (256-bit) or ChaCha20-Poly1305

    You can use the Node.js built-in [`crypto` module](https://nodejs.org/api/crypto.html) for this.

+ An Argon2 implementation

    This package uses [`argon2-browser`], but [`argon2`] is also available.

[encrypted-archive-structure.md]: https://github.com/sounisi5011/npm-packages/blob/main/packages/encrypted-archive/docs/encrypted-archive-structure.md
[`@sounisi5011/encrypted-archive`]: https://github.com/sounisi5011/npm-packages/tree/main/packages/encrypted-archive
[`argon2-browser`]: https://www.npmjs.com/package/argon2-browser
[`argon2`]: https://www.npmjs.com/package/argon2

---

It's interesting that [`@sounisi5011/encrypted-archive`] doesn't work in React Native. I'm not familiar with React Native, but I'll try to fix it as best I can.

If possible, could you please provide the following information?

+ Version of React Native
+ Target platform for your app - iOS, Android, etc.
+ The operating system used to build - In other words, the operating system of the computer you are using to develop.
+ Circumstances in which the problem occurs - When you build, launch an app, try to decrypt, etc.
+ Problem details - Error messages are generated, apps are force-quit, decryption always fails, etc.

**Comment by mikaoelitiana** [comment]
Thank you for your answer @sounisi5011. 

React Native does not have the same modules as nodejs, that's why compatibility is not there by default. Here are some details about my current setup : 
- react native: v0.66
- nodejs: v16
- os: macos 12.01

The problem happens when I try to decrypt a file, just as I import the decrypt function (the app crashes)

**Comment by sounisi5011** [comment]
Interim report: Currently, I'm using React Native, which I built at Expo, to conduct my research. 

+ https://github.com/sounisi5011/react-native-test--using-sounisi5011-encrypted-archive
+ https://github.com/sounisi5011/react-native-test--using-sounisi5011-encrypted-archive/pull/2#issuecomment-991852583

Since the [`@sounisi5011/encrypted-archive`] package was designed for Node.js, it depends on many built-in modules that React Native does not support. These can be solved by editing `metro.config.js`. However, a more serious problem was found. Support is going to take a long time.

[`@sounisi5011/encrypted-archive`]: https://github.com/sounisi5011/npm-packages/tree/main/packages/encrypted-archive

**Comment by mikaoelitiana** [comment]
Thank you for your time @sounisi5011. On my side, I try to implement a decrypt without this package as you described before.

**Comment by sounisi5011** [comment]
I am still aware of this issue. However, I can't fix it for now because I can't build [Native Modules] for React Native.

[Native Modules]: https://reactnative.dev/docs/native-modules-intro

At the very least, [`@sounisi5011/encrypted-archive`] requires an Argon2 library that supports binary data input. However, the React Native-compatible Argon2 library that currently exists in npm only accepts string input. For this reason, I need to choose one of the following:

[`@sounisi5011/encrypted-archive`]: https://github.com/sounisi5011/npm-packages/tree/main/packages/encrypted-archive

1. create my own React Native-compatible Argon2 library
2. send a pull request to the existing Argon2 library
3. wait until React Native supports WebAssembly

At first, I tried 1. However, I could not build React Native on my macOS using XCode and CocoaPods. I get an unknown error, and moreover, the error is not reproducible. I could not even choose 2 because I could not build it in my local environment.

With [react-native-wasm], I can solve this problem without waiting for 3. But methods like [react-native-wasm] use WebView. I think the way a mere encryption/decryption library calls WebView has a fatal negative impact on the performance of an app using [`@sounisi5011/encrypted-archive`].

[react-native-wasm]: https://github.com/inokawa/react-native-wasm

Writing again, *I am still aware of this issue*. I have not forgotten about it.
But now I'm stuck and left it.
I will keep this Issue open until it is resolved, but I don't know when I will be able to resolve it (possibly I will have to get a new Mac to use for development only).
